### ISSUE TITLE
Cannot save NEW files.

### ISSUE THREAD

**Issue by ChillarAnand** [kracekumar/missing-python-mode#2]
If a new file is created on the fly from emacs, it cannot be saved.
Throws error: Cannot revert nonexistent file!

**Comment by jaseemabid** [comment]
I think I fixed this before @kracekumar made this repo. 

See the last diff here: https://gist.github.com/jaseemabid/3def1e104cbff09ad803/revisions

```
-       (add-hook 'before-save-hook 'python-remove-unused-imports)
+      (add-hook 'after-save-hook 'python-remove-unused-imports)
```

**Comment by ChillarAnand** [comment]
Thanks, @jaseemabid
